### ISSUE TITLE
renderError using Found in an Electron project

### ISSUE THREAD

**Issue by adeperio** [4Catalyzer/found-relay#118]
Hi

Currently I am getting an error when using Found in an electron project. It's a 404 error being returned in the renderError function.

Below is my setup code, which is running on the root file loaded by an Electron BrowserWindow.

![image](https://user-images.githubusercontent.com/1326430/35975510-1e0e2130-0d31-11e8-9194-22def6d9a398.png)

This works normally when spun up in a seperate web app in chrome, but in the context of Electron, I get an error in renderError with a 404 status.

Is there any special setup that needs to happen here to get routing to work in an Electron app?

Thanks all

**Comment by jquense** [comment]
Electron uses the `file://` protocol for urls so routing is a bit weird because `/` is not relative to your index.html but to your HD's root folder. In the past I use the MemoryProtocol (with the persist option) instead of the browser one for Electron, that way urls are more of an abstract key than something electron is aware of

**Comment by taion** [comment]
Yup – use `createFarceRouter` and pass in a `MemoryProtocol`: https://github.com/4Catalyzer/found#createfarcerouter

**Comment by adeperio** [comment]
Thanks @jquense and @taion, that all pointed me in the right direction. All working now in Electron :) For those who may be facing a similar problem, I'm now using MemoryProtocol and creating a FarceRouter like so:

![image](https://user-images.githubusercontent.com/1326430/36003735-5e55438e-0d83-11e8-8439-0987cc405cff.png)
