### ISSUE TITLE
Unable to set initial variables for refetchContainer

### ISSUE THREAD

**Issue by BorisTB** [4Catalyzer/found-relay#129]
There should be an option to set initial variables for a route’s refetch container. I need to get a value from a local storage and set it to route to use it as an initial refetch container’s variable so I dont have to call refetch in “componentWillMount”. I thought prepareVariables is for that purpose, but it doesn’t seem to work, initial query is still sent without vars

**Comment by taion** [comment]
You pass down initial variables to the fragments for a refetch container the same way you would for a standard fragment container.

Otherwise the behavior here is the same as if you were using Relay Modern directly.

There's not really a concept of "initial variables" in the same way here anyway. You're really either refetching (with a new query) or you're just rendering the equivalent of a normal fragment container.

**Comment by BorisTB** [comment]
> You pass down initial variables to the fragments for a refetch container the same way you would for a standard fragment container.

I would set these variables on QueryRenderer, so I can reference them in any fragment. Can you please tell me, if this is possible with found-relay?

**Comment by taion** [comment]
In this case you would use `prepareVariables`, yes – just make sure to declare those variables on the query for the route. It should really be the same as for a `<QueryRenderer>`. You just need to make sure `prepareVariables` returns an object with the variables that you want. See the examples in the tests.
