### ISSUE TITLE
Pass variable to fragment in nested route.

### ISSUE THREAD

**Issue by isaldin** [4Catalyzer/found-relay#130]
Hello!
I have root Route with query and nested route with param on it.

```
  <Route
    path="/"
    Component={App}
    query={graphql`
      query routes_App_Query {
        id
        me {
          id
          ...App_me
        }
      }
    `}
  >
    <Route path="store/:storeId" Component={StoreView} />
  </Route>
```
In `StoreView` I wanna to fetch store by id. Fragment looks like:
```
fragment StoreView_store on User {
  store(id: ID!) {
    <some necessary fields>
  }
}
```
How to achieve this? Which way I should go?

**Comment by taion** [comment]
You do it the same way as you would when just using Relay Modern normally, without Found Relay... either use `@argumentDefinitions` on the fragment and pass it down via `@arguments`, or access the global variable without that scoping... in general, though, ID-like things should be queried on the root instead of in component fragments.
